max_timestep = 0.016

[[shaders]]
name = "prepare-map"

[[shaders]]
name = "deferred"

[[shaders]]
name = "emitters"

[[lights]]
name = "fire"
frames = 8
frames_per_second = 8
shape = { type = "Disc", radius = 0.25 }
