[[shaders]]
name = "main"


[[lights]]
name = "fire"
frames = 8


[[stages]]
name = "debug-01"
size = [16, 9]

[[stages.layers]]
tile_name = "wall"
tile_map = """\
x_x_x_x_x_x_x_x_
x_x_x_x_x_x_x_x_
x_x_x_x_x_x_x_x_
x_x_x_x_x_x_x_x_
x_x_x_x_x_x_x_x_
x_x_x_x_x_x_x_x_
x_x_x_x_x_x_x_x_
x_x_x_x_x_x_x_x_
x_x_x_x_x_x_x_x_
"""
z = -0.5

[[stages.layers]]
tile_name = "wall"
tile_map = """\
_x_x_x_x_x_x_x_x
_x_x_x_x_x_x_x_x
_x_x_x_x_x_x_x_x
_x_x_x_x_x_x_x_x
_x_x_x_x_x_x_x_x
_x_x_x_x_x_x_x_x
_x_x_x_x_x_x_x_x
_x_x_x_x_x_x_x_x
_x_x_x_x_x_x_x_x
"""
z = -0.25

[[stages.layers]]
tile_name = "wall"
tile_map = """\
________________
________________
____x___________
__________xx____
_____x____xx____
____xxx_________
_____x__________
________________
________________
"""

[[stages.layers]]
tile_name = "wall"
tile_map = """\
xxxxxxxxxxxxxxxx
x______________x
x______________x
x______________x
x______________x
x______________x
x______________x
x______________x
xxxxxxxxxxxxxxxx
"""
z = 1.0


[[tile_sets]]
name = "wall"
tile_size = [16, 16]


[[tile_sets.tiles]]
x = 0
y = 0
is = ["top", "left"]

[[tile_sets.tiles]]
x = 1
y = 0
is = ["top", "right"]

[[tile_sets.tiles]]
x = 0
y = 1
is = ["bottom", "left"]

[[tile_sets.tiles]]
x = 1
y = 1
is = ["bottom", "right"]


[[tile_sets.tiles]]
x = 2
y = 0
is = ["inner", "bottom", "right"]

[[tile_sets.tiles]]
x = 3
y = 0
is = ["inner", "bottom", "left"]

[[tile_sets.tiles]]
x = 2
y = 1
is = ["inner", "top", "right"]

[[tile_sets.tiles]]
x = 3
y = 1
is = ["inner", "top", "left"]


[[tile_sets.tiles]]
x = 0
y = 2
is = ["right"]

[[tile_sets.tiles]]
x = 1
y = 2
is = ["bottom"]

[[tile_sets.tiles]]
x = 0
y = 3
is = ["top"]

[[tile_sets.tiles]]
x = 1
y = 3
is = ["left"]


[[tile_sets.tiles]]
x = 2
y = 2

[[tile_sets.tiles]]
x = 3
y = 2
weight = 0.2

[[tile_sets.tiles]]
x = 2
y = 3
weight = 0.3

[[tile_sets.tiles]]
x = 3
y = 3
weight = 0.1
