tile_size = 16


[[shaders]]
name = "main"

[[shaders]]
name = "light"


[[lights]]
name = "fire"
frames = 8


[[stages]]
name = "debug-01"
size = [8, 8]

[[stages.layers]]
tile_name = "wall"
tile_map = """\
xxxxxxxx
xxxxxxxx
xxxxxxxx
xxxxxxxx
xxxxxxxx
xxxxxxxx
xxxxxxxx
xxxxxxxx
"""

[[stages.layers]]
tile_name = "wall"
tile_map = """\
xxxxxxxx
x______x
x______x
x______x
x______x
x______x
x______x
xxxxxxxx
"""
z = 0.1


[[tile_sets]]
name = "wall"


[[tile_sets.tiles]]
x = 0
y = 0
is = ["top", "left"]

[[tile_sets.tiles]]
x = 1
y = 0
is = ["top", "right"]

[[tile_sets.tiles]]
x = 0
y = 1
is = ["bottom", "left"]

[[tile_sets.tiles]]
x = 1
y = 1
is = ["bottom", "right"]


[[tile_sets.tiles]]
x = 2
y = 0
is = ["inner", "bottom", "right"]

[[tile_sets.tiles]]
x = 3
y = 0
is = ["inner", "bottom", "left"]

[[tile_sets.tiles]]
x = 2
y = 1
is = ["inner", "top", "right"]

[[tile_sets.tiles]]
x = 3
y = 1
is = ["inner", "top", "left"]


[[tile_sets.tiles]]
x = 0
y = 2
is = ["right"]

[[tile_sets.tiles]]
x = 1
y = 2
is = ["bottom"]

[[tile_sets.tiles]]
x = 0
y = 3
is = ["top"]

[[tile_sets.tiles]]
x = 1
y = 3
is = ["left"]


[[tile_sets.tiles]]
x = 2
y = 2

[[tile_sets.tiles]]
x = 3
y = 2
weight = 0.2

[[tile_sets.tiles]]
x = 2
y = 3
weight = 0.3

[[tile_sets.tiles]]
x = 3
y = 3
weight = 0.1
